src/Hubbup.Web/ViewComponents/NavigationBarViewComponent.cs
using Hubbup.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Hubbup.Web.ViewComponents
{
    public class NavigationBarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string currentGroup = null)
        {
            return View(new NavigationBarViewModel()
            {
                UserName = HttpContext.User.Identity.Name,
                CurrentGroup = currentGroup,
            });
        }
    }
}

src/Hubbup.Web/Pages/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment HostingEnvironment

<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["PageTitlePrefix"] - Hubbup</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" integrity="sha384-ejwKkLla8gPP8t2u0eQyL0Q/4ItcnyveF505U0NIobD/SMsNyXrLti6CWaD0L52l" crossorigin="anonymous">
    <link rel="stylesheet" href="~/app.css" />
</head>
<body>

    @if (!string.Equals(HostingEnvironment.EnvironmentName, "Production", StringComparison.OrdinalIgnoreCase))
    {
        <div class="alert alert-info" style="text-align:center;"><h2>Current environment is: @HostingEnvironment.EnvironmentName</h2></div>
    }

    <header>
        <vc:navigation-bar current-group="@ViewData["CurrentGroup"]" />
    </header>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; <a href="https://github.com/Eilon/Hubbup">Hubbup</a> - GitHub standup tool</p>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    @RenderSection("scripts", required: false)
</body>
</html>