src/WebApplication5/Controllers/IssueListController.cs
using Microsoft.AspNet.Mvc;
using Microsoft.Framework.Configuration;
using Octokit;
using Octokit.Internal;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
    public class IssueListController : Controller
    {
        private static readonly Dictionary<string, string[]> RepoSets = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase)
        {
            {
                "kcore",
                new string[] {
                    "aspnet-docker",
                    "BasicMiddleware",
                    "Caching",
                    //"CoreCLR",
                    "DataProtection",
                    "dnvm",
                    "dnx",
                    "Entropy",
                    "FileSystem",
                    //"Helios",
                    "homebrew-dnx",
                    "Hosting",
                    "HttpAbstractions",
                    "HttpClient",
                    "KestrelHttpServer",
                    "Logging",
                    "Proxy",
                    "ResponseCaching",
                    //"Roslyn",
                    "Security",
                    "ServerTests",
                    "Session",
                    //"Setup",
                    "SignalR-Client-Cpp",
                    "SignalR-Client-Java",
                    "SignalR-Client-JS",
                    "SignalR-Client-Net",
                    "SignalR-Redis",
                    "SignalR-Server",
                    "SignalR-ServiceBus",
                    "SignalR-SqlServer",
                    "Signing",
                    "StaticFiles",
                    "UserSecrets",
                    //"WebListener",
                    "WebSockets",
                }
            },
            {
                "mvc",
                new string[] {
                    "Antiforgery",
                    "Common",
                    "CORS",
                    "DependencyInjection",
                    "Diagnostics",
                    "EventNotification",
                    "jquery-ajax-unobtrusive",
                    "jquery-validation-unobtrusive",
                    "Localization",
                    "MusicStore",
                    "Mvc",
                    "Razor",
                    //"RazorTooling",
                    "Routing",
                }
            },
        };

        public IConfiguration Configuration { get; private set; }

        public IssueListController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        private Task<IReadOnlyList<Issue>> GetIssuesForRepo(string repo)
        {
            // TODO: Change TestApp name

            // TODO: Use GitHub app authorization instead: http://haacked.com/archive/2014/04/24/octokit-oauth/

            var ghc = new GitHubClient(
                new ProductHeaderValue("TestApp"),
                new InMemoryCredentialStore(new Credentials(Configuration["GitHubAuthToken"])));

            var repositoryIssueRequest = new RepositoryIssueRequest
            {
                State = ItemState.Open,
            };
            repositoryIssueRequest.Labels.Add("2 - Working");

            return ghc.Issue.GetAllForRepository("aspnet", repo, repositoryIssueRequest);
        }

        [Route("{repoSet?}")]
        public IActionResult Index(string repoSet)
        {
            var repos =
                RepoSets.ContainsKey(repoSet ?? string.Empty)
                ? RepoSets[repoSet]
                : RepoSets.SelectMany(x => x.Value);

            var allIssuesByRepo = new ConcurrentDictionary<string, Task<IReadOnlyList<Issue>>>();

            Parallel.ForEach(repos, repo => allIssuesByRepo[repo] = GetIssuesForRepo(repo));

            Task.WaitAll(allIssuesByRepo.Select(x => x.Value).ToArray());

            var allIssues = allIssuesByRepo.SelectMany(issueList => issueList.Value.Result.Select(issue => new IssueWithRepo
            {
                Issue = issue,
                RepoName = issueList.Key,
            })).ToList();

            // TODO: Get list of milestones
            // TODO: Client UI to group by person, by repo, or by milestone

            return View(new HomeViewModel
            {
                TotalIssues = allIssues.Count,

                GroupByAssignee = new GroupByAssigneeViewModel
                {
                    Assignees =
                        allIssues
                            .GroupBy(issue => issue.Issue.Assignee.Login)
                            .Select(group =>
                                new GroupByAssigneeAssignee
                                {
                                    Assignee = group.Key,
                                    Issues = group.ToList().AsReadOnly(),
                                })
                            .OrderBy(group => group.Assignee, StringComparer.OrdinalIgnoreCase)
                            .ToList()
                            .AsReadOnly()
                },

                GroupByMilestone = new GroupByMilestoneViewModel
                {
                    Milestones =
                        allIssues
                            .GroupBy(issue => issue.Issue.Milestone.Title)
                            .Select(group =>
                                new GroupByMilestoneMilestone
                                {
                                    Milestone = group.Key,
                                    Issues = group.ToList().AsReadOnly(),
                                })
                            .OrderBy(group => group.Milestone, StringComparer.OrdinalIgnoreCase)
                            .ToList()
                            .AsReadOnly()
                },

                GroupByRepo = new GroupByRepoViewModel
                {
                    Repos =
                        allIssues
                            .GroupBy(issue => issue.RepoName)
                            .Select(group =>
                                new GroupByRepoRepo
                                {
                                    RepoName = group.Key,
                                    Issues = group.ToList().AsReadOnly(),
                                })
                            .OrderByDescending(group => group.Issues.Count)
                            .ToList()
                            .AsReadOnly()
                }
            });
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View("~/Views/Shared/Error.cshtml");
        }
    }
}

src/WebApplication5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - WebApplication5</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
                  asp-fallback-test-class="hidden" asp-fallback-test-property="visibility" asp-fallback-test-value="hidden" />
            <link rel="stylesheet" href="~/css/site.css" asp-file-version="true" />
        </environment>
    </head>
    <body>
        <div class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="IssueList" asp-action="Index" asp-route-repoSet="">All</a></li>
                        <li><a asp-controller="IssueList" asp-action="Index" asp-route-repoSet="kcore">K-Core</a></li>
                        <li><a asp-controller="IssueList" asp-action="Index" asp-route-repoSet="mvc">MVC</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2015 - WebApplication5</p>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.js" asp-file-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>